### ISSUE TITLE
Answer

### ISSUE THREAD

**Issue by Rysakov1986** [voiceip/tinyphone#10]
Please add api for answer.

**Comment by kingster** [comment]
Currently it auto answers incoming calls, are you looking for something else?

**Comment by kingster** [comment]
For manual answer, please look at #11. Is this what you were looking for?

**Comment by Rysakov1986** [comment]
Yes! manual answer, thx!

**Comment by kingster** [comment]
Please do try out the build from the PR #11 and update the [config file](https://raw.githubusercontent.com/voiceip/tinyphone/HEAD/config.json) locally at `C:\Program Files (x86)\Tinyphone\`  to try out the manual answer.

**Comment by kingster** [comment]
Manual answer is now part of the API's. Please try with the latest [binary](https://ci.appveyor.com/project/kingster/tinyphone/build/artifacts) using the [config file](https://raw.githubusercontent.com/voiceip/tinyphone/HEAD/config.json)

In case you have any issues, please report/reopen this issue.
