### ISSUE TITLE
Select account for dail

### ISSUE THREAD

**Issue by Rysakov1986** [voiceip/tinyphone#13]
Hello! How i can use select account for dail? if i have logged more 1 accounts?

```
{
    "accounts": [
        {
            "active": true,
            "id": 0,
            "name": "901@{{host}}",
            "status": "OK",
            "uri": "sip:901@{{host}}"
        },
        {
            "active": true,
            "id": 1,
            "name": "903@{{host}}",
            "status": "OK",
            "uri": "sip:903@{{host}}"
        }
    ],
    "message": "Accounts"
}
```

Thx!

**Comment by kingster** [comment]
This isn't available yet, will get this feature enabled soon.

**Comment by kingster** [comment]
@Rysakov1986 Can you please try with the build from #18 and try dialling call. API contract for dial API has changed.

![image](https://user-images.githubusercontent.com/709368/97835094-644df180-1cff-11eb-81bf-c1d1e8fe0377.png)
