### ISSUE TITLE
编译无法通过

### ISSUE THREAD

**Issue by JDocin** [voiceip/tinyphone#2]
使用vs2015打开pjproject，无法编译成功，报缺库，添加依赖后，又出现这样的错误。
1>pjmedia-x86_64-x64-vc14-Debug.lib(errno.obj) : error LNK2019: 无法解析的外部符号 Pa_GetErrorText，该符号在函数 pjmedia_strerror 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(errno.obj) : error LNK2001: 无法解析的外部符号 Pa_GetErrorText
1>libpjproject-x86_64-x64-vc14-Debug.lib(bcg729.obj) : error LNK2019: 无法解析的外部符号 initBcg729EncoderChannel，该符号在函数 pjmedia_codec_bcg729_init 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(bcg729.obj) : error LNK2019: 无法解析的外部符号 closeBcg729EncoderChannel，该符号在函数 pjmedia_codec_bcg729_init 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(bcg729.obj) : error LNK2019: 无法解析的外部符号 bcg729Encoder，该符号在函数 pjmedia_codec_bcg729_init 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(bcg729.obj) : error LNK2019: 无法解析的外部符号 initBcg729DecoderChannel，该符号在函数 pjmedia_codec_bcg729_init 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(bcg729.obj) : error LNK2019: 无法解析的外部符号 closeBcg729DecoderChannel，该符号在函数 pjmedia_codec_bcg729_init 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(bcg729.obj) : error LNK2019: 无法解析的外部符号 bcg729Decoder，该符号在函数 pjmedia_codec_bcg729_init 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_Initialize，该符号在函数 pjmedia_move_samples 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_Terminate，该符号在函数 pjmedia_move_samples 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_GetHostApiCount，该符号在函数 pjmedia_move_samples 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_GetHostApiInfo，该符号在函数 pa_get_default_input_dev 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_GetDeviceCount，该符号在函数 pjmedia_move_samples 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_RefreshDeviceList，该符号在函数 pjmedia_move_samples 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_GetDeviceInfo，该符号在函数 pjmedia_move_samples 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_OpenStream，该符号在函数 create_rec_stream 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_CloseStream，该符号在函数 pjmedia_move_samples 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_StartStream，该符号在函数 pjmedia_move_samples 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_StopStream，该符号在函数 pjmedia_move_samples 中被引用
1>libpjproject-x86_64-x64-vc14-Debug.lib(pa_dev.obj) : error LNK2019: 无法解析的外部符号 Pa_GetStreamInfo，该符号在函数 pjmedia_move_samples 中被引用

**Comment by kingster** [comment]
Could you please explain the issue in english?

**Comment by kingster** [comment]
This above error looks like linking error due to path mismatch on your system, please double check and run again. For example, follow the docker based build steps.

Please reopen the issue if you still face issue.
