### ISSUE TITLE
Public address or no incoming voice (media delivery issues)

### ISSUE THREAD

**Issue by Rysakov1986** [voiceip/tinyphone#20]
Hello! 
_I was on vacation and now I have checked my incoming calls, everything works great!_

But I have a problem with an incoming voice. (media delivery issues)

I use corp VPN, in microsip "Public address" I select ip corp VPN (172.20.239.15), then there is an incoming voice, if auto, then there is no voice.

In tinyphone, how can I select "Public address"?

I attach tinyphone logs.
[17-11-2020-tinyphone.log](https://github.com/voiceip/tinyphone/files/5553730/17-11-2020-tinyphone.log)

**Comment by kingster** [comment]
Manually configuration of external IP address doesn't look a longterm solution as the vpn IP address would change everytime one reconnects. It seems that you are having misconfigured NAT issue. There are better ways to solve this using STUN/TURN, which the sip protocol supports.

Can you try turning on "stun" in your microsip configuration ( type in your `corp stun endpoint` similar to `stun.l.google.com:19302` in the box)  and in "Public address" leave it as auto, and try a call? If this works for you I can enable stun options on tinyphone.

**Comment by Rysakov1986** [comment]
our company uses Jitsi (or Zoiper before) and it probably automatically uses the 
`SIP UDP Transport Started, **Published Address** 192.168.1.67:5060` // log tiny-softphone 
which is used by VIA.
`Via: SIP / 2.0 / UDP **172.20.239.15**:5060;rport;branch=z9hG4bKPja5b2c3303fec4d558bb21aae378aa8d0`. // log tiny-softphone

Therefore, we don`t use STUN

**Comment by kingster** [comment]
Okay,

I have made changes to use the IP discovered in the registration step to be used in SDP in #21 

Can you please try with the [latest build](https://ci.appveyor.com/project/kingster/tinyphone/builds/36379126/artifacts) of this PR.

**Comment by Rysakov1986** [comment]
Super! I checked it, it works great!
