### ISSUE TITLE
Ring and delay X sec when auto-answer (optional)

### ISSUE THREAD

**Issue by Rysakov1986** [voiceip/tinyphone#23]
Hello!

In the latest version you have disabled ring for auto answer.

But, please tell me, you can add a delay (optional in config.json `autoAnswerDelay: [seconds]`) for auto-answer and if autoAnswerDelay  is enabled (maybe check exist optional autoAnswerDelay and/or autoAnswerDelay > 0 seconds) then play ring?

Thanks!

**Comment by kingster** [comment]
There was never any ring on incoming calls. The last change added ringing sound for cases when auto answer is disabled.

Ring for autoAnswerDelay can certainly be a feature which can be added.

**Comment by Rysakov1986** [comment]
Great news! Looking forward to updating from autoAnswerDelay! Thanks!

**Comment by kingster** [comment]
Hi @Rysakov1986 Can you tryout the build from #25 and test out the feature?

**Comment by Rysakov1986** [comment]
> Hi @Rysakov1986 Can you tryout the build from #25 and test out the feature?

Yes, i go to test feature)

**Comment by Rysakov1986** [comment]
Sorry, I accidentally closed the issue, now I'm checking the feature

**Comment by Rysakov1986** [comment]
The feature works, but this implementation of the feature presents other problems:

1. While waiting, tiny is not available via rest api.
2. If the initiator drops the call while waiting, tiny waits until the timeout expires.

For example, I set a wait for 10 seconds, but I wanted to try to get information about the call, but I didn’t succeed until the waiting time expired. 

And I wanted to try the opportunity until the time ran out of waiting with my manually to answer the call (think that for this I will need to create a new issue, right?).

**Comment by kingster** [comment]
That shouldn't happen, the API shouldn't have blocked. Let me see what the issue is.

**Comment by kingster** [comment]
@Rysakov1986  Can you try with the latest build from the  PR (Build tinyphone 1.0.163) ?

**Comment by Rysakov1986** [comment]
It`s works great! Thanks!!!
