### ISSUE TITLE
WS Not working

### ISSUE THREAD

**Issue by saaiful** [voiceip/tinyphone#38]
jquery.simple.websocket.js:99 WebSocket connection to 'ws://127.0.0.1:6060/events' failed: 

var webSocket = $.simpleWebSocket({ url: 'ws://127.0.0.1:6060/events' });

WebSocket Example is not present.

**Comment by kingster** [comment]
WS by default is disabled which you need to enable by enabling the appropriate `enableWSEvents` flag in config.

**Comment by saaiful** [comment]
enableWSEvents = true 
It works now.

how are you dealing with CROS on XML requests?

**Comment by kingster** [comment]
What do you mean by CORS on XML requests? tinyphone supports cors by responding to OPTIONS request and corresponding headers, so any cors requests should go though. 

Are you facing any specific issue?

**Comment by saaiful** [comment]
> What do you mean by CORS on XML requests? tinyphone supports cors by responding to OPTIONS request and corresponding headers, so any cors requests should go though.
> 
> Are you facing any specific issue?

Sorry, not XML , XHR

**Comment by kingster** [comment]
XHR Requests should go fine. Did you face any issue?

**Comment by saaiful** [comment]
Access to XMLHttpRequest at 'localhost:6060/accounts' from origin 'http://localhost' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, edge, https, chrome-untrusted.

**Comment by saaiful** [comment]
looks like i was missing http :(
Thank again for helping out.
