### ISSUE TITLE
Allow user to manualy specify public address/hostname

### ISSUE THREAD

**Issue by lrrosa** [voiceip/tinyphone#41]
From MicroSIP online help (https://www.microsip.org/help#publicAddress):

Can be used to solve call flow and media delivery issues when you don't have dedicated public IP address. You can manually specify IP address or hostname for Via, Contact and SDP. It can point to one of the interface address OR it can point to the public address of a NAT router where port mappings have been configured.

**Comment by kingster** [comment]
A much easier option is using a `STUN` server, which does this automatically, and tinyphone already support's that. Are you facing any issue with that?

Even their guide refers to the same

> For automatic public address detection and rewrite you can use Allow IP rewrite feature or use STUN server.
