### ISSUE TITLE
Error Dockerfile.base

### ISSUE THREAD

**Issue by daviidmart** [voiceip/tinyphone#43]
I cant build Dockerfile.base pls help

![image](https://user-images.githubusercontent.com/10666050/123308882-d91da800-d4e9-11eb-8287-4b880e64e019.png)

**Comment by daviidmart** [comment]
## Please replace this

\# Install Scoop
RUN powershell.exe -ExecutionPolicy RemoteSigned `
  iex (new-object net.webclient).downloadstring('https://get.scoop.sh');

## For this

\# Install Scoop
RUN powershell.exe [Net.ServicePointManager]::SecurityProtocol =[Net.SecurityProtocolType]::Tls12 ; Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh');

**Comment by kingster** [comment]
Hey!

Thanks for your inputs, there were some more fixes that were required. Have fixed in #45
