### ISSUE TITLE
LINUX

### ISSUE THREAD

**Issue by daviidmart** [voiceip/tinyphone#47]
The project can be compiled for linux?

**Comment by kingster** [comment]
Hi David

Code wise the project could be compiled on Linux as even today it is supported on `macOS`, but the project setup needs to be configured for that. 

Also, the UI features are native to the os, hence those would not be available currently on Linux desktops.

**Comment by kingster** [comment]
Hi @daviidmart 

I have successfully compiled the project using `cmake` on linux (ubuntu) and it should work with any varient in #58 . It's a  cli app since there is no standard UI interface across the linux distributions. 

Is this what you were looking for? Or do you have something else in mind?

**Comment by GowthamX** [comment]
@kingster - Any document or process to follow for linux setup ?

Your windows msi setup is amazing, and loving it.

**Comment by kingster** [comment]
The Linux compilation step are documented [here](https://github.com/voiceip/tinyphone/wiki/Compiling)

>  Your windows msi setup is amazing, and loving it.

Thank you :)
