### ISSUE TITLE
Sending # via dtmf

### ISSUE THREAD

**Issue by fidelitas1894** [voiceip/tinyphone#59]
Hey there maybe iam blind, but is it possible to send a # via dtmf? i  tried it and there is an 404 Error.

I really need to send a # tho

{{host}}:6060/calls/1/dtmf/1 - works
{{host}}:6060/calls/1/dtmf/# - doesnt

**Comment by kingster** [comment]
`#` is a special url character, have you tried escaping it and sending the escaped value?

**Comment by fidelitas1894** [comment]
i've tried to send
{{host}}:6060/calls/1/dtmf/%23

{{host}}:6060/calls/1/dtmf/A
{{host}}:6060/calls/1/dtmf/B
{{host}}:6060/calls/1/dtmf/C
{{host}}:6060/calls/1/dtmf/D
{{host}}:6060/calls/1/dtmf/*

all are working, but i cant get a "#" to play

€ %2523 not working either

**Comment by kingster** [comment]
Hi @fidelitas1894 

Can you install [this version](https://ci.appveyor.com/api/buildjobs/30hbkwtwpclj3k5p/artifacts/tinyphone-installer%2Fbin%2FRelease%2Ftinyphone_installer.msi), and try with `{{host}}:6060/calls/1/dtmf/%23` ?

**Comment by fidelitas1894** [comment]
Hi @kingster 

The new version works like a charm!

Thanks for taking care of the problem that fast! and sorry for the inconvenience.

**Comment by kingster** [comment]
No worries at all! Thanks for the confirmation.
