### ISSUE TITLE
Issue with merging calls for conference

### ISSUE THREAD

**Issue by ploufs** [voiceip/tinyphone#62]
Hello, I'm trying to setup a conference call with Tinyphone and I'm running into an issue with merging multiple calls together.

Here's what I'm trying to do:

1) I do a first call to Tinyphone (call 1)
2) I answer call 1 and put it on hold
4) I do a second call to Tinyphone (call 2)
5) I answer call 2
6) I pass to the conference function the call_id of call 1

The issue is that the two calls are not put in conference together. Am I doing something wrong?

**Comment by kingster** [comment]
Hi @ploufs

This looks odd, could you share a sample sequence of requests, and the logs for that duration?

**Comment by ploufs** [comment]
---http.log---
Request: 127.0.0.1:52848 0118F8C0 HTTP/1.1 POST /calls/0/answer
Response: 0118F8C0 /calls/0/answer 200 0
(2022-06-09 09:38:48) [ERROR   ] StatsD: fail sendto socket not created
(2022-06-09 09:38:48) [ERROR   ] StatsD: fail sendto socket not created
Request: 127.0.0.1:52849 0118D1E8 HTTP/1.1 PUT /calls/0/hold
Response: 0118D1E8 /calls/0/hold 202 0
(2022-06-09 09:38:52) [ERROR   ] StatsD: fail sendto socket not created
(2022-06-09 09:38:52) [ERROR   ] StatsD: fail sendto socket not created
Request: 127.0.0.1:52855 0119DA10 HTTP/1.1 POST /calls/1/answer
Response: 0119DA10 /calls/1/answer 200 0
(2022-06-09 09:39:17) [ERROR   ] StatsD: fail sendto socket not created
(2022-06-09 09:39:17) [ERROR   ] StatsD: fail sendto socket not created
Request: 127.0.0.1:52858 0118D1E8 HTTP/1.1 PUT /calls/0/conference
Response: 0118D1E8 /calls/0/conference 200 0

**Comment by ploufs** [comment]
--tinyphone.log--
[log.txt](https://github.com/voiceip/tinyphone/files/8870959/log.txt)

**Comment by kingster** [comment]
> I pass to the conference function the call_id of call 1

This is what is going on wrong. Call1 is currently on hold, and conference fails. What you should pass is the call_id of call2.

You can verify this info by calling the `http://localhost:6060/calls` and it should return both calls in `NOT_IN_HOLD` state. If either of them is in hold state then that is not participating in the conference. 

That being said, there can be an improvement to handle this, or at least return non2xx in the API. Will take this up in a separate PR

**Comment by ploufs** [comment]
New test :

---http.log---
/calls/0/answer
/calls/1/answer
/calls/1/conference

Call 0 does not have the sound of call 1

**Comment by ploufs** [comment]
File : /tinyphone/phone.cpp
Line 488

BOOST_FOREACH(SIPCall* c, Calls()) { **// all call not only active call**
			if (c->getId() != call->getId()){
				try {
					c->UnHoldCall();
					aud_med2 = call->getAudioMedia(-1); **//replace call by c ?**
					aud_med.startTransmit(aud_med2);
					aud_med2.startTransmit(aud_med);
				} catch(...) {
					PJ_LOG(3, (__FILENAME__, "TinyPhone::Conference getAudioMedia2 Error"));
					return false;
				}
			}
		}

**Comment by kingster** [comment]
Yes, I think you are correct. this is the issue. Let me raise a fix for this.

**Comment by kingster** [comment]
Can you please try with this build? https://ci.appveyor.com/project/kingster/tinyphone/builds/43859131/artifacts

**Comment by ploufs** [comment]
Call 0 now have call 1 sound.

**Comment by kingster** [comment]
Thanks for testing it out. I will go ahead and merge the pr.
