### ISSUE TITLE
How to Install Tinyphone on Ubuntu Linux

### ISSUE THREAD

**Issue by srikanthbvrao** [voiceip/tinyphone#66]
Dear Team,

Can anyone please help, how do I install Tiny phone on Ubuntu Linux?

Thanks and Regards,
Srikanth

**Comment by kingster** [comment]
Hi @srikanthbvrao 

We don't have any GUI version for any Linux Distro currently.  However, a console development version can be [compiled](https://github.com/voiceip/tinyphone/wiki/Compiling#building-on-ubuntu).

**Comment by srikanthbvrao** [comment]
Hi Kingster,

I tried compiling, I am getting below error. But I have "libcryptopp.a" in this folder.

make[2]: *** No rule to make target '/usr/local/lib/libcryptopp.a', needed by 'tinyphone'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/tinyphone.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

rikanth@srikanth-virtual-machine:/usr/src/tinyphone/tinyphone-linux$ sudo cmake ./CMakeLists.txt 
-- Using the single-header code from /usr/src/tinyphone/lib/json/single_include/
CMake Deprecation Warning at /usr/src/tinyphone/lib/statsd-cpp/CMakeLists.txt:9 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/tinyphone/tinyphone-linux
srikanth@srikanth-virtual-machine:/usr/src/tinyphone/tinyphone-linux$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  CMakeLists.txt  console.cpp  Makefile
srikanth@srikanth-virtual-machine:/usr/src/tinyphone/tinyphone-linux$ sudo make
Consolidate compiler generated dependencies of target statsd_static
[ 10%] Built target statsd_static
Consolidate compiler generated dependencies of target tinyphone
make[2]: *** No rule to make target '/usr/local/lib/libcryptopp.a', needed by 'tinyphone'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/tinyphone.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
srikanth@srikanth-virtual-machine:/usr/src/tinyphone/tinyphone-linux$

**Comment by srikanthbvrao** [comment]
Hi Kingster,

I am getting following error now. when I try "make".
----------------------------------------------------------------------------------------
 undefined reference to `boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/tinyphone.dir/build.make:278: tinyphone] Error 1
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/tinyphone.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
-------------------------------------------------------------------------------------------------
------- Below is complete "make" result.


srikanth@srikanth-virtual-machine:/usr/src/tinyphone/tinyphone-linux$ sudo make
[  5%] Building CXX object /usr/src/tinyphone/lib/statsd-cpp/build/CMakeFiles/statsd_static.dir/src/statsd.cpp.o
[ 10%] Linking CXX static library lib/libstatsd_static.a
[ 10%] Built target statsd_static
[ 15%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/account.cpp.o
[ 21%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/baseapp.cpp.o
/usr/src/tinyphone/tinyphone/baseapp.cpp: In function ‘void tp::InitPJSUAEndpoint(std::string)’:
/usr/src/tinyphone/tinyphone/baseapp.cpp:140:71: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  140 |             pj_logerror(pjsip_endpt_create_resolver(endpt, &resolver),"pjsip_endpt_create_resolver");
      |                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 26%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/call.cpp.o
[ 31%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/config.cpp.o
[ 36%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/microtar.cpp.o
[ 42%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/mod_notify.cpp.o
/usr/src/tinyphone/tinyphone/mod_notify.cpp: In function ‘pj_bool_t options_on_rx_request(pjsip_rx_data*)’:
/usr/src/tinyphone/tinyphone/mod_notify.cpp:39:39: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   39 |         const pj_str_t USER_AGENT = { "User-Agent", 10};
      |                                       ^~~~~~~~~~~~
/usr/src/tinyphone/tinyphone/mod_notify.cpp: At global scope:
/usr/src/tinyphone/tinyphone/mod_notify.cpp:59:7: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   59 |     { "mod-notify", 51 },    /* Name.        */
      |       ^~~~~~~~~~~~
[ 47%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/net.cpp.o
[ 52%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/phone.cpp.o
/usr/src/tinyphone/tinyphone/phone.cpp: In member function ‘void tp::TinyPhone::SetCodecs()’:
/usr/src/tinyphone/tinyphone/phone.cpp:39:43: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   39 |                 const pj_str_t ID_ALL = { "*", 1 };
      |                                           ^~~
[ 57%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/server.cpp.o
[ 63%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/stdafx.cpp.o
[ 68%] Building CXX object CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/utils.cpp.o
[ 73%] Building CXX object CMakeFiles/tinyphone.dir/console.cpp.o
[ 78%] Linking CXX executable tinyphone
/usr/bin/ld: CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/account.cpp.o: in function `tp::SIPAccount::onIncomingCall(pj::OnIncomingCallParam&)':
account.cpp:(.text+0x5150): undefined reference to `pjsua_schedule_timer2'
/usr/bin/ld: CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/account.cpp.o: in function `boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const':
account.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition[_ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition]+0xbf): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: account.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition[_ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition]+0xfa): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/account.cpp.o: in function `boost::system::error_category::std_category::equivalent(std::error_code const&, int) const':
account.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0xc0): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: account.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0xfb): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: account.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x1e2): undefined reference to `boost::system::generic_category()'
/usr/bin/ld: CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/baseapp.cpp.o: in function `boost::system::error_code::error_code()':
baseapp.cpp:(.text._ZN5boost6system10error_codeC2Ev[_ZN5boost6system10error_codeC5Ev]+0x1b): undefined reference to `boost::system::system_category()'
/usr/bin/ld: CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/baseapp.cpp.o: in function `boost::asio::error::get_system_category()':
baseapp.cpp:(.text._ZN5boost4asio5error19get_system_categoryEv[_ZN5boost4asio5error19get_system_categoryEv]+0x9): undefined reference to `boost::system::system_category()'
/usr/bin/ld: CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/phone.cpp.o: in function `tp::TinyPhone::ConfigureAudioDevices()':
phone.cpp:(.text+0x5bc4): undefined reference to `pj::AudDevManager::enumDev()'
/usr/bin/ld: CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/server.cpp.o: in function `TinyPhoneHttpServer::Start()::{lambda()#6}::operator()() const':
server.cpp:(.text+0x52d8): undefined reference to `pj::AudDevManager::enumDev()'
/usr/bin/ld: CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/server.cpp.o: in function `unsigned short boost::date_time::month_str_to_ushort<boost::gregorian::greg_month>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
server.cpp:(.text._ZN5boost9date_time19month_str_to_ushortINS_9gregorian10greg_monthEEEtRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5boost9date_time19month_str_to_ushortINS_9gregorian10greg_monthEEEtRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0xbe): undefined reference to `boost::gregorian::greg_month::get_month_map_ptr[abi:cxx11]()'
/usr/bin/ld: CMakeFiles/tinyphone.dir/usr/src/tinyphone/tinyphone/utils.cpp.o: in function `boost::filesystem::create_directory(boost::filesystem::path const&)':
utils.cpp:(.text._ZN5boost10filesystem16create_directoryERKNS0_4pathE[_ZN5boost10filesystem16create_directoryERKNS0_4pathE]+0x1d): undefined reference to `boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/tinyphone.dir/build.make:278: tinyphone] Error 1
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/tinyphone.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Thanks and Regards,
Srikanth

**Comment by kingster** [comment]
Please make sure you install the boost dependencies. From, your logs it seems that some of boost components are missing. 

You can refer to the CI Job https://github.com/voiceip/tinyphone/blob/master/.github/workflows/main.yml#L175-L222 which runs the same sequence of commands to verify that the code compiles. 

Also, the instructions are for ubuntu 20.04. If you are on any other version/distribution you will need to install the dependencies accordingly.

**Comment by srikanthbvrao** [comment]
Hi Kingster,

Thank you very much for your support!  I am able to install now.  Also checking default location for config.json, let me try and register to some SIP Server and come back if I have any doubt.

Thanks and Regards,
Srikanth

**Comment by srikanthbvrao** [comment]
Hi Kingster,

I was able to test all the APIs, thanks very much for your support!

Thanks and Regards,
Srikanth

**Comment by kingster** [comment]
Glad, that I could help.

I am going ahead and closing this issue, as you confirmed that you have been able to compile successfully. Please open a fresh issue if you find any issue.

**Comment by srikanthbvrao** [comment]
Thankyou Kinshukji!

Thanks and Regards,

Srikanth B V  *| *+91 97422 54298 *|* ***@***.***
