### ISSUE TITLE
'enumDev': is not a member of 'pj::AudDevManager'	

### ISSUE THREAD

**Issue by thiva7** [voiceip/tinyphone#77]
hey , i am getting this error when trying to build on this step
# open tinyphone/tinyphone.sln in visual studio 2015 and compile it

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'enumDev': is not a member of 'pj::AudDevManager'	tinyphone	c:\projects\tinyphone\tinyphone\server.cpp	151	

Any idea to fix?

**Comment by kingster** [comment]
`enumDev` comes from the pjsua library. Did you compile the dependencies of the project? Can you share exactly how you are trying to build the project?

**Comment by thiva7** [comment]
Hey ,thanks for reply .
so far i have try multi times and with VS2015 and 2022 , i have follow appveyor.yml#build-step .

pjsua  compile gave me some error each time , so i replace it with 1 that i had from my build for python ( https://stackoverflow.com/questions/54882875/how-to-build-pjsua2-swig-with-visual-studio-2015 )
this way a pass the error...maybe that the issue?

i am trying to get here 
run tinyphone/Debug/tinyphone.exe

i would like to get a version of tinyphone so to not need installer but to start and close app from my app.

here is is when i not change pjsua2 files and errror ,i try again without making anything my self. only set PlatformToolset=v143

# "preperation"
https://pastebin.com/zhjRN4mp

# CURL
https://pastebin.com/hwjSqvQJ

here this line
cmd /c .\libcurl-vc19-x86-release-dll-ipv6-sspi-winssl\bin\curl.exe https://wttr.in/bangalore 
gave path error that path not find

# G729
https://pastebin.com/3gY4R9PX

# cryptopp
https://pastebin.com/5XNgXbXG

# portaudio
https://pastebin.com/YCMJxkyb

# pjsua 
https://pastebin.com/URvjWdiY

here i get error on build 'portaudio.h' related

**Comment by kingster** [comment]
This is due to the project unable to find the required dependencies/files/libraries. In the preparation step, you are using

```
PS C:\projects\tinyphone>   cmd /c subst L: C:\projects\tinyphone
```

This would require that you can the project settings (include paths) from using `E:` drive to `L:` drive.

**Comment by thiva7** [comment]
> This is due to the project unable to find the required dependencies/files/libraries. In the preparation step, you are using
> 
> ```
> PS C:\projects\tinyphone>   cmd /c subst L: C:\projects\tinyphone
> ```
> 
> This would require that you can the project settings (include paths) from using `E:` drive to `L:` drive.

hmm? that n ot true , like i said i follow everystep in appveyor.yml#build-step ,  if i had to re run it in some point dont know that :)

but anyway i made to build it

followed every step but made this msbuild insted
    msbuild /m bcg729.sln /p:Configuration=$BuildMode /p:Platform=Win32 /p:PlatformToolset=v140
    msbuild /m cryptlib.vcxproj /p:Configuration=$BuildMode /p:Platform=Win32 /p:PlatformToolset=v140
    msbuild /m portaudio.sln /p:Configuration=$BuildMode /p:Platform=Win32 /p:PlatformToolset=v140 /p:WindowsTargetPlatformVersion=8.1
    msbuild /m pjproject-vs14.sln -target:libpjproject:Rebuild /p:Configuration=$BuildMode-Static /p:Platform=Win32 /p:PlatformToolset=v140
    msbuild /m statsd-cpp.vcxproj /p:Configuration=$BuildMode /p:Platform=Win32 /p:PlatformToolset=v140 /p:WindowsTargetPlatformVersion=8.1
    msbuild /m tinyphone.sln /p:Configuration=$BuildMode /p:Platform=x86 /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=8.1


and in every step that i got this " Cannot open include file"
i open project file included missing path save and re run build , for me at least that work :)

ps : its possible to disable audio signal?

**Comment by kingster** [comment]
@thiva7, this skips the setup of the `E:` drive which happens on [line 35](https://github.com/voiceip/tinyphone/blob/master/appveyor.yml#L35 ) Which leads to this error. Please follow the guide without skipping any step, alternatively you would have to modify each setup to correct the include directories.
