### ISSUE TITLE
Version 36.0.0.79 error on startup

### ISSUE THREAD

**Issue by akstaffer** [voiceip/tinyphone#8]
Hello, I just downloaded Release version 36.0.0.79 and installed it with the msi file onto Windows 10 Pro. 

When I run Tiny Phone I get the following error.

![Tinyphone Error](https://user-images.githubusercontent.com/24280834/96682297-75752680-132d-11eb-8d24-4bf8e6cf59fb.jpg)

**Comment by kingster** [comment]
Hi

The app tries to download the config file from github.com, does your system have connectivity to internet? Else can you try downloading [the config file](https://raw.githubusercontent.com/voiceip/tinyphone/HEAD/config.json) and putting the folder `C:\Program Files (x86)\Tinyphone\` 

This should solve the error that you  are getting currently.

**Comment by akstaffer** [comment]
Wow!!!!!!!!!!!! Thanks for the instant response! Yes I do have internet. I downloaded the config file and it is now running.

Went to http://localhost:6060/ and got {"message":"Hi!","version":"36.0.0.80"}

But where is the UI, what am I missing?

Thank you so much for your help.

Andrew Staffer
CEO | Qufire Corp
818.693.6643 cell | astaffer@qufire.com<mailto:astaffer@qufire.com>

CONFIDENTIALITY NOTICE: This e-mail message including all attachments is confidential, may be privileged and is intended for the exclusive use of the addressee. Any other person is strictly prohibited from disclosing, distributing or reproducing it. If the addressee cannot be reached or is unknown to you, please inform us immediately and delete this e-mail message and destroy all copies.

**Comment by kingster** [comment]
This softphone is meant to be integrated into existing CRM/Business tools and offers API based functionality, hence there isn't any UI for direct controls. You can refer to the API docs mentioned in the [README](https://github.com/voiceip/tinyphone/blob/master/README.md#apis) to control the softphone. 

If you are looking for a UI based softphone there are multiple alternative options available in the market/opensource community.

**Comment by akstaffer** [comment]
Hello Kinshuk,

Thank you for the quick response!!!! I now understand. I’ll check it out! Do you do any node.js coding? Are you interested in some contract work?

Best Regards,

Andrew Staffer
CEO | Qufire Corp
818.693.6643 cell | astaffer@qufire.com<mailto:astaffer@qufire.com>

CONFIDENTIALITY NOTICE: This e-mail message including all attachments is confidential, may be privileged and is intended for the exclusive use of the addressee. Any other person is strictly prohibited from disclosing, distributing or reproducing it. If the addressee cannot be reached or is unknown to you, please inform us immediately and delete this e-mail message and destroy all copies.

**Comment by akstaffer** [comment]
Hello Kinshuk,

Would you be willing to do some custom coding work for the existing Tinyphone and also do consulting concerning SIP on a contract basis.

Thank you,

Andrew Staffer
CEO | Qufire Corp
818.693.6643 cell | astaffer@qufire.com<mailto:astaffer@qufire.com>

CONFIDENTIALITY NOTICE: This e-mail message including all attachments is confidential, may be privileged and is intended for the exclusive use of the addressee. Any other person is strictly prohibited from disclosing, distributing or reproducing it. If the addressee cannot be reached or is unknown to you, please inform us immediately and delete this e-mail message and destroy all copies.


From: Andrew Staffer
Sent: Wednesday, October 21, 2020 6:23 PM
To: 'voiceip/tinyphone' <reply@reply.github.com>; voiceip/tinyphone <tinyphone@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [voiceip/tinyphone] Version 36.0.0.79 error on startup (#8)

Hello Kinshuk,

Thank you for the quick response!!!! I now understand. I’ll check it out! Do you do any node.js coding? Are you interested in some contract work?

Best Regards,

Andrew Staffer
CEO | Qufire Corp
818.693.6643 cell | astaffer@qufire.com<mailto:astaffer@qufire.com>

CONFIDENTIALITY NOTICE: This e-mail message including all attachments is confidential, may be privileged and is intended for the exclusive use of the addressee. Any other person is strictly prohibited from disclosing, distributing or reproducing it. If the addressee cannot be reached or is unknown to you, please inform us immediately and delete this e-mail message and destroy all copies.
