### ISSUE TITLE
Question: Can I connect my VOIP

### ISSUE THREAD

**Issue by addyuchiha** [voiceip/tinyphone#82]
I mean I have a VoIP providers so, can i connect it in this?

**Comment by kingster** [comment]
Yes, you can connect any VoIP provider with this softphone. Once configured use `/login` API to configure the softphone with the credentials, and your VoIP account should be ready to use.

**Comment by addyuchiha** [comment]
I am also having some problem in installing it

**Comment by addyuchiha** [comment]
I cant install it I have used the msi installer but When I open the application, it shows errors

**Comment by kingster** [comment]
What error do you get? Can you share some screenshot of the error / copy paste the error message that you are getting?

**Comment by AddyBlaze** [comment]
itss my alt accc this is the error-
![Annotation 2023-11-30 075404](https://github.com/voiceip/tinyphone/assets/90613114/bae9d5f8-7eb6-49db-9a41-3e34f0701fb3)

**Comment by kingster** [comment]
Does this system have access to Internet? By default, the configuration is downloaded from the git repo. Alternatively, it can be also be placed in the installation folder. Please follow the [installation instructions](https://github.com/voiceip/tinyphone?tab=readme-ov-file#installation) and create `config.json` with appropriate configuration

**Comment by addyuchiha** [comment]
yes it is connected to the internet, I first downloaded the msi instaler and run it and then this error occured
