### ISSUE TITLE
Question: Which codecs is supported (OSX version)?? Only G729? 

### ISSUE THREAD

**Issue by vitekcz1** [voiceip/tinyphone#85]
Hi, after more experimenting I would like to force TinyPhone to load my local config.json. But unable to find a way where to put the file. TinyPhone is loading config from online.

**Comment by kingster** [comment]
Hi

You should be able to use your own `config.json` by placing them beside the executable. 

On Windows that would mean, putting it in `C:\Program Files (x86)\Tinyphone\` 
On OSx that would mean `/Applications/Tinyphone.app/Contents/MacOS`

You can refer to [Installation Instructions](https://github.com/voiceip/tinyphone?tab=readme-ov-file#installation) for more guide
